stages:
  split:
    cmd: python src/train_test_split.py -i dataset/Crop_recommendation.csv -o dataset/split
    deps:
    - dataset/Crop_recommendation.csv
    - src/train_test_split.py
    outs:
    - dataset/split
