stages:
  Exploratory_Data_Analysis:
    cmd: python src/EDA.py -i dataset/Crop_recommendation.csv -o charts
    deps:
    - dataset/Crop_recommendation.csv
    - src/EDA.py
    outs:
    - charts
  split:
    cmd: python src/train_test_split.py -i dataset/Crop_recommendation.csv -o dataset/split
    deps:
    - dataset/Crop_recommendation.csv
    - src/train_test_split.py
    outs:
    - dataset/split
  modelBuilder:
    cmd: python src/knn.py -i dataset/split -o models
    deps:
    - dataset/split
    - src/knn.py
    outs:
    - models
  Evaluator:
    cmd: python src/evaluate.py -i dataset/split -m models
    deps:
    - dataset/split
    - src/evaluate.py
    - models
